### PR TITLE
feat(shipstation/api):update to python3 add some helper methods

### PR DESCRIPTION
**Pull request by vpatel85**

### CODE REVIEW

**Comment by natecox** [comment]
So I let this slide for way too long, sorry about that.

It looks like you added a couple of methods; can you add them to the readme as well so they don't go undocumented? Once we have that I'm fine merging this in.

Edit: Actually, probably best to add test coverage for them as well.

**Comment by vpatel85** [comment]
@natecox agreed, will add docs and tests when i get a chance, thanks for following up.

**Comment by natecox** [comment]
@vpatel85 I just noticed that this is merging into `master`. I'm using git flow for this project, can you submit a PR to merge into develop?

**Comment by natecox** [comment]
Closing for inactivity, feel free to reopen when you're ready.

**Pull request closed without merging**
